### ISSUE TITLE
Python Best Practices for a New Project in 2021

### ISSUE THREAD

**Issue by qiwihui** [qiwihui/pocket_readings#1148]
The goal of this tutorial is to describe Python development ecosystem. It can be helpful for someone coming to Python from another programming language.<br>
<br>
Tags: python<br>
<br>
via Pocket https://ift.tt/3yBsFAn original site<br>
<br>
July 06, 2021 at 11:38AM

**Comment by MarthinusBosman** [comment]
Personal preference: I'd use prospector instead of flake8. It opens up the door for a lot more tools if you ever need them as well as not needing to additionally install mypy.

Also, I think VS Code should automatically detect poetry environments these days, or it's a fair argument to make to use `virtualenvs.in-project = true` configuration in poetry
